### ISSUE TITLE
Readme workflow assumes `set-workspace-p`

### ISSUE THREAD

**Issue by Croissong** [alphapapa/bufler.el#12]
Hi!

After reading the Workflow section in the Readme, I expected `bufler-switch-buffer` to only offer me buffers in the group on subsequent calls, as described in step 4 & 5.  
It seems it will only work as described when either `bufler-workspace-switch-buffer-sets-workspace` or `SET-WORKSPACE-P` is true.
 
I think defaulting `bufler-workspace-switch-buffer-sets-workspace` to `t` might be sensible, since the user expects the described workflow without any configuration. What do you think?

On a related note, I also expected selecting a buffer via `bufler-list` to automatically set the workspace.

Awesome package, keep up the good work!

**Comment by alphapapa** [comment]
Hi Jan,

Thanks for reporting the discrepancy.  It's easy for me to forget to update the docs when the code is changing quickly as I'm exploring how it should work.  I think this should make the description accurate to the current code.

> I think defaulting bufler-workspace-switch-buffer-sets-workspace to t might be sensible, since the user expects the described workflow without any configuration. What do you think?

I don't think that should be the default, because IME, I'm often switching to buffers in other workspaces, like `*scratch*`, `*messages*`, help buffers, etc, while I'm working in one workspace's buffers.  If the workspace switched every time, that would negate the benefit of `bufler-switch-buffer`'s presenting the active workspace's buffers by default.

In fact, now that I've been using it for a while, I think that option should probably be removed, because I don't think it makes sense to switch the workspace every time `bufler-switch-buffer` is called.  Please read the new workflow description and let me know if you still think it's a useful option to have.

> On a related note, I also expected selecting a buffer via bufler-list to automatically set the workspace.

No, that's what the `f` and `F` bindings are for.  I think the most frequent need is to simply switch to a buffer, not to switch to a buffer *and* change the workspace.  If the workspace changed every time the buffer changed, I think that would negate much of the benefit of having workspaces.

All that said, I'm only one user, and there are other workflows, so I'm interested to hear about them and how Bufler may support a wider range of them, and even enable new ones.

Thanks for the kind words.  Your feedback is very valuable.  Please keep sending it!

**Comment by Croissong** [comment]
Thanks for the super quick response and changes.
I had just started using this package and after starting to figure out my own workflow I agree with your points.
I'll gladly report my experiences, since I've been hoping for this kind of package a long time :)
I've previously been using [persp-mode](https://github.com/Bad-ptr/persp-mode.el) but never quite managed to make it work for me.

**Comment by alphapapa** [comment]
Great, thanks.  Yes, I had always wanted some kind of workspace manager that didn't require me to manually place buffers into workspaces every time or manually define a workspace for every project/directory/mode.  So far this seems to be working well.
