### ISSUE TITLE
Faces don't show until magit is loaded

### ISSUE THREAD

**Issue by TheBB** [alphapapa/bufler.el#15]
You're using some faces from *magit.el* but don't take care to load that file, resulting in some fairly bland buffer lists until it is loaded by some other action.

**Comment by alphapapa** [comment]
Hi,

You're right that I left a few references to the `magit-head` face in there.  Thanks for reporting that.

However, I don't know what you mean about a bland-looking list, because those faces should be overridden by other faces that are applied later.  Just now I tested installing Bufler into a clean Emacs config, without Magit installed, and `bufler-list` looks the same as when Magit is installed and loaded.  Would you please show me a screenshot of what you mean?

Thanks.

**Comment by TheBB** [comment]
This is what I'm observing: https://www.youtube.com/watch?v=hdL1NlZjMEU

**Comment by alphapapa** [comment]
Oh, you're talking about the `bufler-switch-buffer` command.  I don't know why you are seeing that.  Those colors you see after loading `magit` are not the `magit-head` face, anyway.

Here's what I see testing in a clean Emacs config: https://www.reddit.com/user/github-alphapapa/comments/fkd4al/example/

**Comment by alphapapa** [comment]
I've removed the references to the `magit-head` face.  But those were vestigal, anyway, and I can't reproduce the problem you describe.  Please let me know if it still happens and you can help me reproduce it.
