### ISSUE TITLE
bufler-list-buffer-kill occasionally leaves an open row

### ISSUE THREAD

**Issue by gonewest818** [alphapapa/bufler.el#21]
I apologize in advance that I can't make this happen reliably, but it seems `bufler-list-buffer-kill` sometimes leaves a nearly-empty row in the `*Bufler*` window.

For instance:
<img width="636" alt="Screen Shot 2020-03-19 at 3 54 39 PM" src="https://user-images.githubusercontent.com/2460918/77122245-5eb6cc00-69fa-11ea-89f4-ecd7f7ff6c26.png">

That blank row was the `*Warnings*` buffer with size 95, and I just killed it (`k`).   Once I refresh the buffer (`g`) this row will get be cleaned up.  I'll keep watching for ways to repeat this. So far I think it has always been special buffers, not file-backed buffers, but I might be wrong about that.

**Comment by alphapapa** [comment]
Hi Neil,

Yes, I've seen this myself sometimes.  I think that using `C-u g` corrects it it when `g` doesn't.

I have some notes in the code about it, see https://github.com/alphapapa/bufler.el/blob/39e756a23196d12792a3af4a06ab024d8235ee19/bufler.el#L281.  I'm not sure what the cause is: it might be related to how the return value of `buffer-list` is hashed, which Bufler uses to determine whether the list of buffers has changed, or it might be caused by the `bufler-list` buffer itself causing references to killed buffers to be retained.  I don't know why it seems to be intermittent, though.

You might try disabling `bufler-use-cache` and see if that stops it from happening.  If it does, and if performance is still good enough, we could consider disabling caching by default (for `bufler-cache`; `bufler-cache-related-dirs-p` would remain enabled).

Thanks.

**Comment by gonewest818** [comment]
ok, I just disabled `bufler-use-cache` to see what happens.

Incidentally, in my experience when this happens it's the last buffer in a particular group. I haven't yet seen this happen for a buffer that occurs in the middle of a group.  I did just see it happen twice in the same group (I killed the last buffer, it left behind a partial entry, I killed the buffer above that, and it also left behind a partial entry).

**Comment by alphapapa** [comment]
Thanks.  I thought I had added code to avoid inserting rows for killed buffers, but apparently something else is going on.

**Comment by gonewest818** [comment]
Hey, by the way, when I said “it happened twice in the same group” that was **before** disabling `bufler-use-cache`. Not that I think of it, I haven’t seen an instance of the big since then.

**Comment by alphapapa** [comment]
I think that should fix it even with `bufler-use-cache` enabled.  Please let me know if that's the case.  Thanks for your help.

**Comment by gonewest818** [comment]
Thanks! I will update and see.
