### ISSUE TITLE
Q: how to group files that share the same magit-git-dir

### ISSUE THREAD

**Issue by stsquad** [alphapapa/bufler.el#43]
I'm sure this must be possible but I'm not sure how you express it in the group syntax. I want all buffers associated with the same (magit-git-dir) to be grouped together. This is instead of having stuff configured using projectile or project.

Do I need to define another bufler-defauto-group macro?

**Comment by alphapapa** [comment]
The `auto-project` group should cover this.  It's not necessarily to configure `project` manually.  It automatically detects git repos.

**Comment by stsquad** [comment]
Hmm project doesn't seem to do that - I wonder if it's because I've stamped on vc-mode?

**Comment by alphapapa** [comment]
Stamped?

**Comment by stsquad** [comment]
(project-current) returns nil for all my files. The reason being because it relies on vc-mode and I disable it:

    ;; I only really use git, stamp on vc-mode....
    (with-eval-after-load 'vc
      (remove-hook 'find-file-hook 'vc-find-file-hook)
      (remove-hook 'find-file-hook 'vc-refresh-state)
      (setq vc-handled-backends 'nil))

so it sounds like the best fix is to come up with a magit equivalent for project-find-functions so bufler can use the existing infrastructure.

**Comment by alphapapa** [comment]
I see.  Curious, why do you do that?  Is having `vc-refresh-state` in `find-file-hook` a performance issue?

Anyway, if you disable `vc` like that, and you don't want to use Projectile either, then I guess you will need to define another auto group, like you said.  You could simply copy the `auto-project` definition and have it call `magit-git-dir` instead of the `project` functions.  

For now, you would also need to add a corresponding entry to the macro `bufler-defgroups`.  When I convert the package to using `bufler-group-tree-defmacro`, I'll try to make it easier to define custom groups.

**Comment by stsquad** [comment]
It kept getting in the way, especially over tramp connections. In the end I just squashed it because I never used it and everything I care about is in a git repository already. So I did this:

    (defun my-git-project-finder (dir)
      "Integrate .git project roots."
      (let ((dotgit (and (setq dir (locate-dominating-file dir ".git"))
                         (expand-file-name dir))))
        (and dotgit
             (cons 'transient (file-name-directory dotgit)))))

    (add-hook 'project-find-functions 'my-git-project-finder)

And now buffler behaves like I want it to. I'm wondering if there is something we could document or if I'm just a weird outlier who doesn't use vc-mode ;-)

**Comment by alphapapa** [comment]
That's a clever solution.  I don't know if it's common to disable vc-mode like that.  I'll retitle this issue so it can serve to document it.  If it turns out to be a frequent issue, maybe it could go in the readme.  Thanks!
