### ISSUE TITLE
Warnings with bufler-switch-buffer

### ISSUE THREAD

**Issue by jmburgos** [alphapapa/bufler.el#73]
Hello @alphapapa,

I just installed bufler, and when I ran `buffler-switch-buffer` I get multiples instances of the following warning:

```
Warning: Eager macro-expansion skipped due to cycle:
  … => (load "bufler-workspace-tabs.el") => (macroexpand-all …) => (macroexpand (eval-when-compile …)) => (load "bufler-workspace-tabs.el")
Eager macro-expansion failure: (error "Recursive load" "/home/julian/.emacs.d/elpa/bufler-20210722.1703/bufler-workspace.elc" "/home/julian/.emacs.d/elpa/bufler-20210722.1703/bufler-workspace-tabs.el" "/home/julian/.emacs.d/elpa/bufler-20210722.1703/bufler-workspace.elc" "/home/julian/.emacs.d/elpa/bufler-20210722.1703/bufler-workspace-tabs.el" "/home/julian/.emacs.d/elpa/bufler-20210722.1703/bufler-workspace.elc" "/home/julian/.emacs.d/elpa/bufler-20210722.1703/bufler-workspace-tabs.el" "/home/julian/.emacs.d/elpa/bufler-20210722.1703/bufler-workspace.elc" "/home/julian/.emacs.d/elpa/bufler-20210722.1703/bufler-workspace-tabs.el" "/home/julian/.emacs.d/elpa/bufler-20210722.1703/bufler-workspace.elc")
```
Do you know what could be the issue?

**Comment by alphapapa** [comment]
Hi Julian,

Macro expansion issues usually result from installation or configuration problems.  You didn't mention how you installed the package or what version of Emacs you're using, so I'm going to take a wild guess that you're using Doom or Spacemacs, or something like that, from whose users I often get reports like this.  In that case, I'd suggest making sure that you're installing according to those systems' documentation.  

If you're not using them, then I'd suggest trying to reproduce the problem by installing into a clean Emacs configuration, e.g. using https://github.com/alphapapa/emacs-sandbox.sh.  As far as I know, the package works, because I've never seen errors like the ones you showed.

I also notice that some of the file paths in the error are compiled ELC files, while others are uncompiled EL files.  That probably indicates an interrupted compilation process, so some kind of installation problem.

**Comment by jmburgos** [comment]
Thank you for your answer.  I am using vanilla emacs, so there must be something in my config file.  I will test with emacs -q and will let you know how it goes.
________________________________

**Comment by alphapapa** [comment]
FYI, this is being tracked in #70.  The short answer appears to be:

1.  Update package `map` from GNU ELPA.
2. Reinstall Bufler.
